query getCommentsForThePost($skip: Int, $limit: Int, $postId: String!) {
  getCommentsForThePost(skip: $skip, limit: $limit, postId: $postId) {
    comments{
      text
      id
      isCurrentUserAuthor
      hasCurrentUserLikedComment
      likeCount
      authorDetails {
        name
        username
        profileImage
        id
      }
    }
  }
}