query getFeed(
  $textPostSkip: Int
  $imagePostSkip: Int
  $videoPostSkip: Int
  $limit: Int
) {
  getFeed(
    textPostSkip: $textPostSkip
    imagePostSkip: $imagePostSkip
    videoPostSkip: $videoPostSkip
    limit: $limit
  ) {
    posts
    postsType
  }
}
