query getImagePost($identifier: String!) {
  getImagePost(identifier: $identifier) {
    image
    caption
    authorDetails {
      name
      username
      profileImage
      id
    }
    isCurrentUserAuthor
    hasCurrentUserLikedImage
  }
}
