query getImagePost($identifier: String!) {
  getImagePost(identifier: $identifier) {
    id
    image
    caption
    authorDetails {
      name
      username
      profileImage
      id
    }
    isCurrentUserAuthor
    hasCurrentUserLikedImage
    likeCount
    commentCount
    uri
    updatedAt
  }
}
